import type { Config } from 'tailwindcss'

// Barcelona Noir — extracted from DESIGN.md
const config: Config = {
  content: ['./src/**/*.{ts,tsx,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:                   '#F8F5EE',
        surface:                      '#F8F5EE',
        'surface-dim':                '#EDE8DF',
        'surface-bright':             '#FFFFFF',
        'surface-container-lowest':   '#FFFFFF',
        'surface-container-low':      '#F5F0E8',
        'surface-container':          '#EDE8DF',
        'surface-container-high':     '#E5DFD5',
        'surface-container-highest':  '#DDD7CC',
        'surface-variant':            '#E8E2D8',

        primary:                      '#8C2A2A',
        'primary-container':          '#F5E6E6',
        'primary-fixed':              '#F5E6E6',
        'primary-fixed-dim':          '#D4A0A0',
        'on-primary':                 '#FFFFFF',
        'on-primary-container':       '#5C1010',
        'on-primary-fixed':           '#5C1010',
        'on-primary-fixed-variant':   '#7A1A1A',
        'inverse-primary':            '#E8A0A0',
        'surface-tint':               '#8C2A2A',

        secondary:                    '#6E6356',
        'secondary-container':        '#EDE8DF',
        'secondary-fixed':            '#DDD7CC',
        'secondary-fixed-dim':        '#C8BFB2',
        'on-secondary':               '#FFFFFF',
        'on-secondary-container':     '#221E1A',
        'on-secondary-fixed':         '#221E1A',
        'on-secondary-fixed-variant': '#3D3830',

        tertiary:                     '#9F9486',
        'tertiary-container':         '#EDE8DF',
        'tertiary-fixed':             '#DDD7CC',
        'tertiary-fixed-dim':         '#C8BFB2',
        'on-tertiary':                '#FFFFFF',
        'on-tertiary-container':      '#221E1A',
        'on-tertiary-fixed':          '#221E1A',
        'on-tertiary-fixed-variant':  '#3D3830',

        'on-surface':                 '#221E1A',
        'on-surface-variant':         '#6E6356',
        'on-background':              '#221E1A',
        'inverse-surface':            '#221E1A',
        'inverse-on-surface':         '#F8F5EE',

        outline:                      '#9F9486',
        'outline-variant':            '#C8BFB2',

        error:                        '#B3261E',
        'error-container':            '#F9DEDC',
        'on-error':                   '#FFFFFF',
        'on-error-container':         '#410E0B',
      },
      fontFamily: {
        display:    ['"Instrument Serif"', 'Georgia', 'serif'],
        h1:         ['Inter', 'sans-serif'],
        h2:         ['Inter', 'sans-serif'],
        'body-lg':  ['Inter', 'sans-serif'],
        'body-md':  ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display:   ['48px', { lineHeight: '1.1',  letterSpacing: '-0.04em', fontWeight: '800' }],
        h1:        ['32px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '700' }],
        h2:        ['24px', { lineHeight: '1.3',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6',  letterSpacing: '0',       fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6',  letterSpacing: '0',       fontWeight: '400' }],
        'label-sm':['12px', { lineHeight: '1',    letterSpacing: '0.05em',  fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:  '0.25rem',
        md:  '0.75rem',
        lg:  '0.5rem',
        xl:  '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs:   '4px',
        sm:   '8px',
        base: '6px',
        gutter: '12px',
        md:   '16px',
        lg:   '24px',
        xl:   '32px',
        'container-padding': '16px',
      },
    },
  },
  plugins: [],
}

export default config
