package com.clubfuoco.app.core.components

/**
 * A country code with its dialling prefix, flag, and the maximum number of
 * NATIONAL digits — the dial code excluded. The digit count caps input, which is
 * what stops someone typing their number twice into the same field.
 *
 * Generated from `PhoneNumberField.swift`'s list rather than retyped, so the two
 * platforms cannot drift. Regenerate if that list changes.
 */
data class Country(
    val name: String,
    val flag: String,
    val dialCode: String,
    val digits: Int,
) {
    val key: String get() = name + dialCode
}

private fun C(name: String, flag: String, dialCode: String, digits: Int) =
    Country(name, flag, dialCode, digits)

/**
 * The full list. Barcelona-relevant markets lead; everything else follows
 * alphabetically. The picker is searchable, so ordering only decides what a
 * first-time scroll sees.
 */
val COUNTRIES: List<Country> = listOf(
    C("Spain", "🇪🇸", "+34", 9),
    C("United Kingdom", "🇬🇧", "+44", 10),
    C("France", "🇫🇷", "+33", 9),
    C("Germany", "🇩🇪", "+49", 11),
    C("Italy", "🇮🇹", "+39", 10),
    C("Portugal", "🇵🇹", "+351", 9),
    C("Ireland", "🇮🇪", "+353", 9),
    C("Netherlands", "🇳🇱", "+31", 9),
    C("Belgium", "🇧🇪", "+32", 9),
    C("Switzerland", "🇨🇭", "+41", 9),
    C("Austria", "🇦🇹", "+43", 13),
    C("Sweden", "🇸🇪", "+46", 9),
    C("Norway", "🇳🇴", "+47", 8),
    C("Denmark", "🇩🇰", "+45", 8),
    C("Finland", "🇫🇮", "+358", 10),
    C("Poland", "🇵🇱", "+48", 9),
    C("Czechia", "🇨🇿", "+420", 9),
    C("Greece", "🇬🇷", "+30", 10),
    C("Romania", "🇷🇴", "+40", 9),
    C("United States", "🇺🇸", "+1", 10),
    C("Canada", "🇨🇦", "+1", 10),
    C("Mexico", "🇲🇽", "+52", 10),
    C("Brazil", "🇧🇷", "+55", 11),
    C("Argentina", "🇦🇷", "+54", 10),
    C("Colombia", "🇨🇴", "+57", 10),
    C("Morocco", "🇲🇦", "+212", 9),
    C("United Arab Emirates", "🇦🇪", "+971", 9),
    C("Australia", "🇦🇺", "+61", 9),
    C("Afghanistan", "🇦🇫", "+93", 9),
    C("Albania", "🇦🇱", "+355", 9),
    C("Algeria", "🇩🇿", "+213", 9),
    C("Andorra", "🇦🇩", "+376", 6),
    C("Angola", "🇦🇴", "+244", 9),
    C("Antigua and Barbuda", "🇦🇬", "+1", 10),
    C("Armenia", "🇦🇲", "+374", 8),
    C("Aruba", "🇦🇼", "+297", 7),
    C("Azerbaijan", "🇦🇿", "+994", 9),
    C("Bahamas", "🇧🇸", "+1", 10),
    C("Bahrain", "🇧🇭", "+973", 8),
    C("Bangladesh", "🇧🇩", "+880", 10),
    C("Barbados", "🇧🇧", "+1", 10),
    C("Belarus", "🇧🇾", "+375", 9),
    C("Belize", "🇧🇿", "+501", 7),
    C("Benin", "🇧🇯", "+229", 8),
    C("Bhutan", "🇧🇹", "+975", 8),
    C("Bolivia", "🇧🇴", "+591", 8),
    C("Bosnia and Herzegovina", "🇧🇦", "+387", 8),
    C("Botswana", "🇧🇼", "+267", 8),
    C("Brunei", "🇧🇳", "+673", 7),
    C("Bulgaria", "🇧🇬", "+359", 9),
    C("Burkina Faso", "🇧🇫", "+226", 8),
    C("Burundi", "🇧🇮", "+257", 8),
    C("Cambodia", "🇰🇭", "+855", 9),
    C("Cameroon", "🇨🇲", "+237", 9),
    C("Cape Verde", "🇨🇻", "+238", 7),
    C("Cayman Islands", "🇰🇾", "+1", 10),
    C("Central African Republic", "🇨🇫", "+236", 8),
    C("Chad", "🇹🇩", "+235", 8),
    C("Chile", "🇨🇱", "+56", 9),
    C("China", "🇨🇳", "+86", 11),
    C("Comoros", "🇰🇲", "+269", 7),
    C("Congo - Brazzaville", "🇨🇬", "+242", 9),
    C("Congo - Kinshasa", "🇨🇩", "+243", 9),
    C("Costa Rica", "🇨🇷", "+506", 8),
    C("Côte d’Ivoire", "🇨🇮", "+225", 10),
    C("Croatia", "🇭🇷", "+385", 9),
    C("Cuba", "🇨🇺", "+53", 8),
    C("Cyprus", "🇨🇾", "+357", 8),
    C("Djibouti", "🇩🇯", "+253", 8),
    C("Dominica", "🇩🇲", "+1", 10),
    C("Dominican Republic", "🇩🇴", "+1", 10),
    C("Ecuador", "🇪🇨", "+593", 9),
    C("Egypt", "🇪🇬", "+20", 10),
    C("El Salvador", "🇸🇻", "+503", 8),
    C("Equatorial Guinea", "🇬🇶", "+240", 9),
    C("Eritrea", "🇪🇷", "+291", 7),
    C("Estonia", "🇪🇪", "+372", 8),
    C("Eswatini", "🇸🇿", "+268", 8),
    C("Ethiopia", "🇪🇹", "+251", 9),
    C("Fiji", "🇫🇯", "+679", 7),
    C("Gabon", "🇬🇦", "+241", 8),
    C("Gambia", "🇬🇲", "+220", 7),
    C("Georgia", "🇬🇪", "+995", 9),
    C("Ghana", "🇬🇭", "+233", 9),
    C("Gibraltar", "🇬🇮", "+350", 8),
    C("Grenada", "🇬🇩", "+1", 10),
    C("Guatemala", "🇬🇹", "+502", 8),
    C("Guinea", "🇬🇳", "+224", 9),
    C("Guinea-Bissau", "🇬🇼", "+245", 9),
    C("Guyana", "🇬🇾", "+592", 7),
    C("Haiti", "🇭🇹", "+509", 8),
    C("Honduras", "🇭🇳", "+504", 8),
    C("Hong Kong", "🇭🇰", "+852", 8),
    C("Hungary", "🇭🇺", "+36", 9),
    C("Iceland", "🇮🇸", "+354", 9),
    C("India", "🇮🇳", "+91", 10),
    C("Indonesia", "🇮🇩", "+62", 11),
    C("Iran", "🇮🇷", "+98", 10),
    C("Iraq", "🇮🇶", "+964", 10),
    C("Israel", "🇮🇱", "+972", 9),
    C("Jamaica", "🇯🇲", "+1", 10),
    C("Japan", "🇯🇵", "+81", 10),
    C("Jordan", "🇯🇴", "+962", 9),
    C("Kazakhstan", "🇰🇿", "+7", 10),
    C("Kenya", "🇰🇪", "+254", 9),
    C("Kiribati", "🇰🇮", "+686", 8),
    C("Kuwait", "🇰🇼", "+965", 8),
    C("Kyrgyzstan", "🇰🇬", "+996", 9),
    C("Laos", "🇱🇦", "+856", 10),
    C("Latvia", "🇱🇻", "+371", 8),
    C("Lebanon", "🇱🇧", "+961", 8),
    C("Lesotho", "🇱🇸", "+266", 8),
    C("Liberia", "🇱🇷", "+231", 9),
    C("Libya", "🇱🇾", "+218", 10),
    C("Liechtenstein", "🇱🇮", "+423", 9),
    C("Lithuania", "🇱🇹", "+370", 8),
    C("Luxembourg", "🇱🇺", "+352", 11),
    C("Macau", "🇲🇴", "+853", 8),
    C("Madagascar", "🇲🇬", "+261", 9),
    C("Malawi", "🇲🇼", "+265", 9),
    C("Malaysia", "🇲🇾", "+60", 10),
    C("Maldives", "🇲🇻", "+960", 7),
    C("Mali", "🇲🇱", "+223", 8),
    C("Malta", "🇲🇹", "+356", 8),
    C("Marshall Islands", "🇲🇭", "+692", 7),
    C("Mauritania", "🇲🇷", "+222", 8),
    C("Mauritius", "🇲🇺", "+230", 8),
    C("Micronesia", "🇫🇲", "+691", 7),
    C("Moldova", "🇲🇩", "+373", 8),
    C("Monaco", "🇲🇨", "+377", 9),
    C("Mongolia", "🇲🇳", "+976", 8),
    C("Montenegro", "🇲🇪", "+382", 9),
    C("Mozambique", "🇲🇿", "+258", 9),
    C("Myanmar", "🇲🇲", "+95", 10),
    C("Namibia", "🇳🇦", "+264", 10),
    C("Nauru", "🇳🇷", "+674", 7),
    C("Nepal", "🇳🇵", "+977", 10),
    C("New Zealand", "🇳🇿", "+64", 10),
    C("Nicaragua", "🇳🇮", "+505", 8),
    C("Niger", "🇳🇪", "+227", 8),
    C("Nigeria", "🇳🇬", "+234", 10),
    C("North Korea", "🇰🇵", "+850", 10),
    C("North Macedonia", "🇲🇰", "+389", 8),
    C("Oman", "🇴🇲", "+968", 8),
    C("Pakistan", "🇵🇰", "+92", 10),
    C("Palau", "🇵🇼", "+680", 7),
    C("Palestine", "🇵🇸", "+970", 9),
    C("Panama", "🇵🇦", "+507", 8),
    C("Papua New Guinea", "🇵🇬", "+675", 8),
    C("Paraguay", "🇵🇾", "+595", 9),
    C("Peru", "🇵🇪", "+51", 9),
    C("Philippines", "🇵🇭", "+63", 10),
    C("Qatar", "🇶🇦", "+974", 8),
    C("Russia", "🇷🇺", "+7", 10),
    C("Rwanda", "🇷🇼", "+250", 9),
    C("Saint Kitts and Nevis", "🇰🇳", "+1", 10),
    C("Saint Lucia", "🇱🇨", "+1", 10),
    C("Saint Vincent and the Grenadines", "🇻🇨", "+1", 10),
    C("Samoa", "🇼🇸", "+685", 7),
    C("San Marino", "🇸🇲", "+378", 10),
    C("São Tomé and Príncipe", "🇸🇹", "+239", 7),
    C("Saudi Arabia", "🇸🇦", "+966", 9),
    C("Senegal", "🇸🇳", "+221", 9),
    C("Serbia", "🇷🇸", "+381", 9),
    C("Seychelles", "🇸🇨", "+248", 7),
    C("Sierra Leone", "🇸🇱", "+232", 8),
    C("Singapore", "🇸🇬", "+65", 8),
    C("Slovakia", "🇸🇰", "+421", 9),
    C("Slovenia", "🇸🇮", "+386", 8),
    C("Solomon Islands", "🇸🇧", "+677", 7),
    C("Somalia", "🇸🇴", "+252", 8),
    C("South Africa", "🇿🇦", "+27", 9),
    C("South Korea", "🇰🇷", "+82", 10),
    C("South Sudan", "🇸🇸", "+211", 9),
    C("Sri Lanka", "🇱🇰", "+94", 9),
    C("Sudan", "🇸🇩", "+249", 9),
    C("Suriname", "🇸🇷", "+597", 7),
    C("Syria", "🇸🇾", "+963", 9),
    C("Taiwan", "🇹🇼", "+886", 9),
    C("Tajikistan", "🇹🇯", "+992", 9),
    C("Tanzania", "🇹🇿", "+255", 9),
    C("Thailand", "🇹🇭", "+66", 9),
    C("Timor-Leste", "🇹🇱", "+670", 8),
    C("Togo", "🇹🇬", "+228", 8),
    C("Tonga", "🇹🇴", "+676", 7),
    C("Trinidad and Tobago", "🇹🇹", "+1", 10),
    C("Tunisia", "🇹🇳", "+216", 8),
    C("Turkey", "🇹🇷", "+90", 10),
    C("Turkmenistan", "🇹🇲", "+993", 8),
    C("Tuvalu", "🇹🇻", "+688", 6),
    C("Uganda", "🇺🇬", "+256", 9),
    C("Ukraine", "🇺🇦", "+380", 9),
    C("Uruguay", "🇺🇾", "+598", 8),
    C("Uzbekistan", "🇺🇿", "+998", 9),
    C("Vanuatu", "🇻🇺", "+678", 7),
    C("Vatican City", "🇻🇦", "+379", 10),
    C("Venezuela", "🇻🇪", "+58", 10),
    C("Vietnam", "🇻🇳", "+84", 10),
    C("Yemen", "🇾🇪", "+967", 9),
    C("Zambia", "🇿🇲", "+260", 9),
    C("Zimbabwe", "🇿🇼", "+263", 9),)

/**
 * Longest dial code first.
 *
 * Load-bearing for parsing a stored number: "+1" is a prefix of "+1..." but so
 * is nothing else, while "+34" and "+345" would both match a Spanish number if
 * tested in list order. Matching longest-first resolves the overlap the only way
 * that is correct.
 */
val COUNTRIES_BY_DIAL_LENGTH: List<Country> = COUNTRIES.sortedByDescending { it.dialCode.length }
