import { createServiceClient } from '@/lib/supabase/server'
import { requirePortal } from '@/lib/portal-auth'
import { getBrand } from '@/lib/partner'
import { sendSupplierPasswordSetup } from '@/lib/email'
import { logAudit } from '@/lib/portal-audit'
import { ok, err } from '@/lib/utils'

// Where the set-password email lands. Canonical production origin (not the
// request origin, which could be a preview/localhost) so the emailed link is
// always the live page. This path must be in Supabase Auth → Redirect URLs.
const SET_PASSWORD_URL = 'https://clubfuoco.com/supplier/set-password'

// POST /api/portal/brands/:id/provision-login — grant a supplier access to the
// FuocoPromoters app and email them a "create your password" link via Resend.
//   • new email  → Supabase invite link (also creates the account)
//   • known email → Supabase recovery link (set/replace password)
// The link is GENERATED by Supabase (not sent by it) and delivered through
// Resend — our email infrastructure. The account is marked a pre-approved
// promoter and linked to the brand via owner_user_id. Re-POSTing an already
// provisioned brand just resends the link.
export async function POST(
  _req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const denied = await requirePortal()
  if (denied) return denied
  const { id } = await params
  const sb = await createServiceClient()

  const brand = await getBrand(sb, id)
  if (!brand) return err('Brand not found', 404)
  const email = brand.login_email?.trim().toLowerCase()
  if (!email) return err('Set a login email for this brand first')

  const isReset = !!(await sb.from('users').select('id').eq('email', email).maybeSingle()).data

  // Generate (don't send) the set-password link. invite creates a new account;
  // recovery targets the existing one. Both carry the redirect to our page.
  const { data: linkData, error: linkGenErr } = await sb.auth.admin.generateLink({
    type: isReset ? 'recovery' : 'invite',
    email,
    options: { redirectTo: SET_PASSWORD_URL },
  })
  const actionLink = linkData?.properties?.action_link
  const userId = linkData?.user?.id
  if (linkGenErr || !actionLink || !userId) {
    return err(linkGenErr?.message ?? 'Could not generate the set-password link', 500)
  }

  // Don't let one login own two brands — the supplier UI resolves exactly one.
  const { data: clash } = await sb
    .from('partner_brands')
    .select('id, name')
    .eq('owner_user_id', userId)
    .neq('id', id)
    .maybeSingle()
  if (clash) return err(`That login is already linked to “${(clash as { name: string }).name}”`)

  // Pre-approve as a promoter so the app admits them, and link the brand.
  const { error: userErr } = await sb.from('users')
    .update({ account_kind: 'promoter', is_promoter: true })
    .eq('id', userId)
  if (userErr) return err(userErr.message, 500)

  const { error: linkErr } = await sb.from('partner_brands')
    .update({ owner_user_id: userId })
    .eq('id', id)
  if (linkErr) return err(linkErr.message, 500)

  // Deliver via Resend. If email isn't configured the account is still linked —
  // tell the operator so they don't assume a mail went out.
  const emailSent = await sendSupplierPasswordSetup({
    to: email, brandName: brand.name, actionLink, isReset,
  })

  await logAudit(sb, { action: 'brand.provision', summary: `Sent “${brand.name}” a ${isReset ? 'password-reset' : 'set-password'} link (${email})`, target_type: 'brand', target_id: id, meta: { email, emailSent } })
  return ok({ provisioned: true, email, emailKind: isReset ? 'reset' : 'invite', emailSent })
}

// DELETE /api/portal/brands/:id/provision-login — revoke access. Unlinks the
// brand from its account (leaves the account itself intact).
export async function DELETE(
  _req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const denied = await requirePortal()
  if (denied) return denied
  const { id } = await params
  const sb = await createServiceClient()
  const brand = await getBrand(sb, id)
  const { error } = await sb.from('partner_brands').update({ owner_user_id: null }).eq('id', id)
  if (error) return err(error.message, 500)
  await logAudit(sb, { action: 'brand.revoke', summary: `Revoked app access for “${brand?.name ?? id}”`, target_type: 'brand', target_id: id })
  return ok({ revoked: true })
}
