#!/usr/bin/env python3
"""
Generate Android string resources from the iOS String Catalog.

The catalog in ios-native is the single source of truth for copy — it is what
`gen-xcstrings.js` builds from the web dictionaries, so translations land there
first. This script is the Android leg: run it after any copy change and the
four values*/strings.xml files are rewritten from scratch.

    python3 scripts/gen-strings.py

Key mapping: iOS keys are dotted ("explore.savedMany"), which Android resource
names cannot contain, so dots become underscores ("explore_savedMany"). Case is
preserved deliberately — it keeps a 1:1 mental mapping with the Swift call
sites, which matters a lot while porting 30 screens.

Format strings: iOS `%@` is Objective-C for "any object" and becomes `%s`.
Android additionally REQUIRES positional arguments once a string takes more
than one, so any multi-arg string is rewritten to `%1$s` / `%2$d` form in
catalog order. Strings carrying a literal, unescaped `%` and no arguments at
all are marked formatted="false" so the toolchain stops treating the percent as
a malformed specifier.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CATALOG = os.path.normpath(os.path.join(
    HERE, "..", "..", "ios-native", "ClubFuoco", "Core", "Localization",
    "Localizable.xcstrings"))
RES = os.path.normpath(os.path.join(HERE, "..", "app", "src", "main", "res"))

# English is the default (values/); the rest get a locale-qualified folder.
LOCALE_DIRS = {"en": "values", "es": "values-es", "ca": "values-ca", "fr": "values-fr"}

# A real printf specifier. `%%` is a literal percent and must not match, so it
# is consumed first by the alternation.
#
# The space flag is deliberately NOT in the flag set. It is legal printf, but no
# app copy ever means it — and with it included, "15% discount on bookings"
# parses as a `% d` specifier, which silently turns three literal percentages
# into one-argument format strings.
SPEC = re.compile(r"%%|%([-+#0]*\d*(?:\.\d+)?)([@a-zA-Z])")


def android_key(ios_key: str) -> str:
    return ios_key.replace(".", "_")


def convert_format(value: str, positional: bool) -> str:
    """Rewrite iOS specifiers to Android ones, numbering them when required."""
    index = [0]

    def sub(m: re.Match) -> str:
        if m.group(0) == "%%":
            return "%%"
        flags, conv = m.group(1), m.group(2)
        conv = "s" if conv == "@" else conv
        index[0] += 1
        pos = f"{index[0]}$" if positional else ""
        return f"%{pos}{flags}{conv}"

    return SPEC.sub(sub, value)


def arg_count(value: str) -> int:
    return sum(1 for m in SPEC.finditer(value) if m.group(0) != "%%")


def has_bare_percent(value: str) -> bool:
    """A `%` that is neither an escaped `%%` nor part of a specifier."""
    return "%" in SPEC.sub("", value)


def escape(value: str) -> str:
    """XML + Android string escaping."""
    value = (value.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;"))
    value = value.replace("\\", "\\\\") if "\\" in value else value
    value = value.replace("'", "\\'").replace('"', '\\"')
    value = value.replace("\n", "\\n")
    return value


def main() -> int:
    if not os.path.exists(CATALOG):
        print(f"catalog not found: {CATALOG}", file=sys.stderr)
        return 1

    strings = json.load(open(CATALOG, encoding="utf-8"))["strings"]

    # Arity is decided from English and applied to every locale, so a
    # translation can never disagree with its own base string about whether
    # arguments are positional.
    arity = {k: arg_count(v["localizations"]["en"]["stringUnit"]["value"])
             for k, v in strings.items()}

    written = {}
    for locale, folder in LOCALE_DIRS.items():
        out = [
            '<?xml version="1.0" encoding="utf-8"?>',
            "<!-- GENERATED by scripts/gen-strings.py from the iOS String",
            "     Catalog. Do not edit by hand: edit",
            "     ios-native/ClubFuoco/Core/Localization/Localizable.xcstrings",
            "     and re-run the script. -->",
            "<resources>",
        ]
        count = 0
        for ios_key in sorted(strings):
            unit = strings[ios_key]["localizations"].get(locale)
            if not unit:
                continue  # falls back to values/ at runtime
            raw = unit["stringUnit"]["value"]
            n = arity[ios_key]
            value = convert_format(raw, positional=n > 1)
            attrs = ""
            if n == 0 and has_bare_percent(raw):
                attrs = ' formatted="false"'
            out.append(f'    <string name="{android_key(ios_key)}"{attrs}>'
                       f"{escape(value)}</string>")
            count += 1
        out.append("</resources>")
        out.append("")

        path = os.path.join(RES, folder, "strings.xml")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(out))
        written[folder] = count

    for folder, count in written.items():
        print(f"  {folder}/strings.xml — {count} strings")
    multi = sorted(k for k, n in arity.items() if n > 1)
    print(f"positional (multi-arg) keys: {', '.join(multi) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
